n = int(input('escreva um numero para ver a tabuada desse numero: '))
a, b, c, d, e, f ,g ,h ,i = (n * 1, n * 2, n * 3, n * 4, n * 5, n * 6, n * 7, n * 8, n * 9)
print('=' * 18)
print('A tabuada do ',n)
print('{}x{} = {} '.format(n, '1', a))
print('{}x{} = {} '.format(n, '2', b))
print('{}x{} = {} '.format(n, '3', c))
print('{}x{} = {} '.format(n, '4', d))
print('{}x{} = {} '.format(n, '5', e))
print('{}x{} = {} '.format(n, '6', f))
print('{}x{} = {} '.format(n, '7', g))
print('{}x{} = {} '.format(n, '8', h))
print('{}x{} = {} '.format(n, '9', i))